---
  - name: Install NPM
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - nodejs
      - npm
    become: true

  - name: Install Elasticdump
    npm:
      name: elasticdump
      version: "3.1.0"
      global: yes
    become: true